Drop rows where EmployeeName and JobTitle are 'Not provided'

Replace 'Not Provided' with 0 in BasePay OvertimePay	OtherPay	Benefits

Change BasePay	OvertimePay	OtherPay	Benefits type to float

Display all employees name and basepay columns who have a BasePay greater than 200,000.

Find all employees whose JobTitle contains the word “Manager” (case = False)

Retrieve only the columns: EmployeeName, JobTitle, and TotalPay.

Find count of employees who have zero OvertimePay.

Calculate the TotalPay for each JobTitle where totalpay > 300000

Find the top 5 JobTitles with the highest average TotalPayBenefits show in descending order

Replace all missing Benefits values with 0

Identify the top employee name by TotalPay in each Year. Show year, employeename and totalpay dataframe

Find the number of employees per JobTitle.

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Salaries - Salaries.csv to Salaries - Salaries.csv

In [5]:
df = pd.read_csv('Salaries - Salaries.csv')
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,NaN,San Francisco,PT

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

In [8]:
df.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [13]:
df[['EmployeeName', 'JobTitle']]

             EmployeeName                                        JobTitle
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
...                   ...                                             ...
148649      Roy I Tillery                                       Custodian
148650                NaN                                             NaN
148651                NaN                                             NaN
148652                NaN                                             NaN
148653          Joe Lopez                      Counselor, Log Cabin Ranch

[148654 rows x 2 columns]

In [14]:
#Drop rows where EmployeeName and JobTitle are 'Not provided'
df['EmployeeName'], df['JobTitle'] = df['EmployeeName'].replace('Not provided', np.nan), df['JobTitle'].replace('Not provided', np.nan)
df[['EmployeeName', 'JobTitle']]

             EmployeeName                                        JobTitle
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
...                   ...                                             ...
148649      Roy I Tillery                                       Custodian
148650                NaN                                             NaN
148651                NaN                                             NaN
148652                NaN                                             NaN
148653          Joe Lopez                      Counselor, Log Cabin Ranch

[148654 rows x 2 columns]

In [17]:
#Replace 'Not Provided' with 0 in BasePay OvertimePay OtherPay Benefits
#Change BasePay OvertimePay OtherPay Benefits type to float
cols = ['BasePay', 'OvertimePay', 'OtherPay', 'Benefits']
df[cols] = df[cols].replace('Not Provided', 0).astype(float)

In [18]:
df[['BasePay','OvertimePay', 'OtherPay', 'Benefits']]

          BasePay  OvertimePay   OtherPay  Benefits
0       167411.18         0.00  400184.25       NaN
1       155966.02    245131.88  137811.38       NaN
2       212739.13    106088.18   16452.60       NaN
3        77916.00     56120.71  198306.90       NaN
4       134401.60      9737.00  182234.59       NaN
...           ...          ...        ...       ...
148649       0.00         0.00       0.00       0.0
148650       0.00         0.00       0.00       0.0
148651       0.00         0.00       0.00       0.0
148652       0.00         0.00       0.00       0.0
148653       0.00         0.00    -618.13       0.0

[148654 rows x 4 columns]

In [19]:
#Display all employees name and basepay columns who have a BasePay greater than 200,000
df[df['BasePay'] > 200000][['EmployeeName', 'BasePay']]

              EmployeeName    BasePay
2           ALBERT PARDINI  212739.13
7            DAVID KUSHNER  256576.96
9       JOANNE HAYES-WHITE  285262.00
12       EDWARD HARRINGTON  294580.02
13             JOHN MARTIN  271329.03
...                    ...        ...
110953      Ronald P Flynn  201296.01
110954    Sheryl L Bregman  201296.00
110976       Susan T Obata  202445.22
110977       John O Funghi  201181.01
111107       Mayra T Vivas  205036.00

[509 rows x 2 columns]

In [20]:
#Find all employees whose JobTitle contains the word “Manager” (case = False)
df[df['JobTitle'].str.contains('Manager', case=False, na=False)]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
83,84,EDWARD REISKIN,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,230827.12,0.0,0.00,NaN,230827.12,230827.12,2011,NaN,San Francisco,NaN
87,88,KEVIN BARRY,MANAGER VII,96814.36,0.0,133563.47,NaN,230377.83,230377.83,2011,NaN,San Francisco,NaN
95,96,MIVIC HIROSE,MANAGER VIII,215180.76,0.0,12000.00,NaN,227180.76,227180.76,2011,NaN,San Francisco,NaN
162,163,JULIE LABONTE,MANAGER VIII,207501.20,0.0,2903.37,NaN,210404.57,210404.57,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147216,147217,Steven D Koneffklatt,Manager III,0.00,0.0,1890.72,342.03,1890.72,2232.75,2014,NaN,San Francisco,PT
147502,147503,Alice B Villagomez,Manager IV,1660.00,0.0,0.00,16.60,1660.00,1676.60,2014,NaN,San Francisco,PT
147805,147806,Stephen C Laplante,Manager II,0.00,0.0,982.62,177.76,982.62,1160.38,2014,NaN,San Francisco,PT
148150,148151,Shirley M Parker,Real Property Manager,0.00,0.0,647.76,0.00,647.76,647.76,2014,NaN,San Francisco,PT
148475,148476,James P Horan,Manager IV,175.75,0.0,0.00,1.41,175.75,177.16,2014,NaN,San Francisco,PT

In [21]:
#Retrieve only the columns: EmployeeName, JobTitle, and TotalPay.
df[['EmployeeName', 'JobTitle', 'TotalPay']]

,EmployeeName,JobTitle,TotalPay
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),538909.28
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),335279.91
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,332343.61
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",326373.19
...,...,...,...
148649,Roy I Tillery,Custodian,0.00
148650,NaN,NaN,0.00
148651,NaN,NaN,0.00
148652,NaN,NaN,0.00
148653,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13

In [22]:
#Find count of employees who have zero OvertimePay.
df[df['OvertimePay'] == 0].shape[0]

77325

In [23]:
#Calculate the TotalPay for each JobTitle where totalpay > 300000
df[df['TotalPay'] > 300000 ][['JobTitle', 'TotalPay']]

                                              JobTitle   TotalPay
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19
...                                                ...        ...
110540                    Asst Chf of Dept (Fire Dept)  329390.54
110542                     Senior Physician Specialist  311650.36
110543                                     Commander 3  322143.10
110545                  Battalion Chief, Fire Suppress  307099.61
110546                  Battalion Chief, Fire Suppress  306117.53

[61 rows x 2 columns]

In [24]:
#Find the top 5 JobTitles with the highest average TotalPayBenefits show in descending order
df.groupby('JobTitle')['TotalPayBenefits'].mean().sort_values(ascending=False).head(5)

JobTitle
Chief Investment Officer                          436224.360000
Chief of Police                                   411732.266667
Chief, Fire Department                            408865.326667
GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY    399211.275000
Gen Mgr, Public Trnsp Dept                        380696.440000
Name: TotalPayBenefits, dtype: float64

In [30]:
#Replace all missing Benefits values with 0
df['Benefits'] = df['Benefits'].replace(np.nan, 0)
df.Benefits

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
148649    0.0
148650    0.0
148651    0.0
148652    0.0
148653    0.0
Name: Benefits, Length: 148654, dtype: float64

In [31]:
#Identify the top employee name by TotalPay in each Year. Show year, employeename and totalpay dataframe
df.loc[df.groupby('Year')['TotalPay'].idxmax(), ['Year', 'EmployeeName', 'TotalPay']]

        Year    EmployeeName   TotalPay
0       2011  NATHANIEL FORD  567595.43
36159   2012  Gary Altenberg  362844.66
72927   2013     Samson  Lai  347102.32
110531  2014     David Shinn  471952.64

In [32]:
#Find the number of employees per JobTitle.
df['JobTitle'].value_counts()

JobTitle
Transit Operator                   7036
Special Nurse                      4389
Registered Nurse                   3736
Public Svc Aide-Public Works       2518
Police Officer 3                   2421
                                   ...
TREE TOPPER SUPERVISOR II             1
TRAINING TECHNICIAN                   1
COURT AD RESOLUTION COORDINATOR       1
ROOFER SUPERVISOR I                   1
POWER PLANT SUPERVISOR I              1
Name: count, Length: 2158, dtype: int64

In [33]:
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,0.0,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,0.0,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,0.0,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,0.0,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,0.0,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,NaN,NaN,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,NaN,NaN,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,NaN,NaN,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,PT